### ISSUE TITLE
Add support for dead-letter queues

### ISSUE THREAD

**Issue by satabin** [commercetools/fs2-queues#10]
Provide a common API to create and setup dead-letter queues.
```[tasklist]
### Tasks
- [ ] Define a common model
- [ ] Add possibility to add dead-letter policy add queue creation
- [ ] Add dead-letter queue creation API
- [ ] Ensure the processing pipes work well with the dead-letter policy
```
